"""add custom questions to jobs and applications

Revision ID: 319a59817f19
Revises: 455f2c49a998
Create Date: 2025-12-15 18:17:55.927566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319a59817f19'
down_revision: Union[str, Sequence[str], None] = '455f2c49a998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('question_answers', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_applications_applied_at'), table_name='applications')
    op.drop_index(op.f('idx_applications_job_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_job_status'), table_name='applications')
    op.drop_index(op.f('idx_applications_status'), table_name='applications')
    op.drop_index(op.f('idx_applications_user_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_user_status'), table_name='applications')
    op.drop_index(op.f('idx_bookmarks_created_at'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_job_id'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_user_id'), table_name='bookmarks')
    op.add_column('jobs', sa.Column('custom_questions', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_jobs_active_created'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_employer_id'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_location'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_title'), table_name='jobs')
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    op.drop_index(op.f('idx_users_is_employer'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_is_employer'), 'users', ['is_employer'], unique=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('idx_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('idx_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('idx_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('idx_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('idx_jobs_employer_id'), 'jobs', ['employer_id'], unique=False)
    op.create_index(op.f('idx_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('idx_jobs_active_created'), 'jobs', ['is_active', 'created_at'], unique=False)
    op.drop_column('jobs', 'custom_questions')
    op.create_index(op.f('idx_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_job_id'), 'bookmarks', ['job_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('idx_applications_user_status'), 'applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('idx_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('idx_applications_job_status'), 'applications', ['job_id', 'status'], unique=False)
    op.create_index(op.f('idx_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('idx_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.drop_column('applications', 'question_answers')
    # ### end Alembic commands ###
