"""add salary, type and requirements column to jobs

Revision ID: 5d7da493dfd1
Revises: a3e968f73069
Create Date: 2025-11-24 15:54:21.381787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7da493dfd1'
down_revision: Union[str, Sequence[str], None] = 'a3e968f73069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'Type')
    op.drop_column('jobs', 'salary')
    # ### end Alembic commands ###
