"""rename Type to job_type in jobs table

Revision ID: c79e87dc30a5
Revises: 5d7da493dfd1
Create Date: 2025-11-25 07:18:22.760041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79e87dc30a5'
down_revision: Union[str, Sequence[str], None] = '5d7da493dfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.String(), nullable=True))
    op.drop_column('jobs', 'Type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###
